#cloud-config
autoinstall:
    version: 1
    interactive-sections:
      - keyboard
      - storage
    identity:
      realname: 'Nova Singular'
      hostname: dev-workstation
      username: nova_singular
      password: '$y$j9T$se5GiRmIwVj9kLwISmUWG/$tx26L2xjDDt0Q8mut0ZG6/w8ZogwlB.u0vYwpkpK7U2'
    locale: en_US.UTF-8
    keyboard:
      layout: br
      variant: abnt2-nodeadkeys
    timezone: America/Sao_Paulo
    storage: {}
    codecs:
      install: true
    drivers:
      install: true
    updates: security
    shutdown: reboot
  
    late-commands:
      # Download post install script, set ownership and permissions
      - curtin in-target --target=/target -- /bin/bash -c "wget -O /home/nova_singular/Desktop/post-install-setup.sh https://raw.githubusercontent.com/Quemuel-Nassor/SO-Scripts/refs/heads/master/Linux/post-install-setup.sh && chown nova_singular:nova_singular /home/nova_singular/Desktop/post-install-setup.sh && chmod +x /home/nova_singular/Desktop/post-install-setup.sh"

      # Create autostart directory
      - curtin in-target --target=/target -- /bin/bash -c "mkdir -p /home/nova_singular/.config/autostart"

      # Create autostart desktop entry for first login execution
      - curtin in-target --target=/target -- /bin/bash -c "cat > /home/nova_singular/.config/autostart/post-install-setup.desktop <<EOF
[Desktop Entry]
Type=Application
Exec=pkexec /home/nova_singular/Desktop/post-install-setup.sh && rm -- "\$HOME/.config/autostart/post-install-setup.desktop"
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name=Post Install Setup (root)
Comment=Run post install setup script once at first login as root
EOF"

      # Fix ownership for autostart directory and script
      - curtin in-target --target=/target -- /bin/bash -c "chown -R nova_singular:nova_singular /home/nova_singular/.config/autostart /home/nova_singular/Desktop/post-install-setup.sh"
